<?php
/**
 * Vnfendpointrequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  tpn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Telstra Programmable Network API
 *
 * Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.
 *
 * OpenAPI spec version: 2.4.2
 * Contact: pnapi-support@team.telstra.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace tpn\Model;

use \ArrayAccess;
use \tpn\ObjectSerializer;

/**
 * Vnfendpointrequest Class Doc Comment
 *
 * @category Class
 * @package  tpn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Vnfendpointrequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'vnfendpointrequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'customeruuid' => 'string',
        'imageuuid' => 'int',
        'flavoruuid' => 'int',
        'datacenteruuid' => 'string',
        'config' => 'string',
        'topology_tag_uuid' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'customeruuid' => null,
        'imageuuid' => 'int32',
        'flavoruuid' => 'int32',
        'datacenteruuid' => null,
        'config' => null,
        'topology_tag_uuid' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'customeruuid' => 'customeruuid',
        'imageuuid' => 'imageuuid',
        'flavoruuid' => 'flavoruuid',
        'datacenteruuid' => 'datacenteruuid',
        'config' => 'config',
        'topology_tag_uuid' => 'topology_tag_uuid'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'customeruuid' => 'setCustomeruuid',
        'imageuuid' => 'setImageuuid',
        'flavoruuid' => 'setFlavoruuid',
        'datacenteruuid' => 'setDatacenteruuid',
        'config' => 'setConfig',
        'topology_tag_uuid' => 'setTopologyTagUuid'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'customeruuid' => 'getCustomeruuid',
        'imageuuid' => 'getImageuuid',
        'flavoruuid' => 'getFlavoruuid',
        'datacenteruuid' => 'getDatacenteruuid',
        'config' => 'getConfig',
        'topology_tag_uuid' => 'getTopologyTagUuid'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['customeruuid'] = isset($data['customeruuid']) ? $data['customeruuid'] : null;
        $this->container['imageuuid'] = isset($data['imageuuid']) ? $data['imageuuid'] : null;
        $this->container['flavoruuid'] = isset($data['flavoruuid']) ? $data['flavoruuid'] : null;
        $this->container['datacenteruuid'] = isset($data['datacenteruuid']) ? $data['datacenteruuid'] : null;
        $this->container['config'] = isset($data['config']) ? $data['config'] : null;
        $this->container['topology_tag_uuid'] = isset($data['topology_tag_uuid']) ? $data['topology_tag_uuid'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['customeruuid'] === null) {
            $invalidProperties[] = "'customeruuid' can't be null";
        }
        if ($this->container['imageuuid'] === null) {
            $invalidProperties[] = "'imageuuid' can't be null";
        }
        if ($this->container['flavoruuid'] === null) {
            $invalidProperties[] = "'flavoruuid' can't be null";
        }
        if ($this->container['datacenteruuid'] === null) {
            $invalidProperties[] = "'datacenteruuid' can't be null";
        }
        if ($this->container['config'] === null) {
            $invalidProperties[] = "'config' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets customeruuid
     *
     * @return string
     */
    public function getCustomeruuid()
    {
        return $this->container['customeruuid'];
    }

    /**
     * Sets customeruuid
     *
     * @param string $customeruuid customeruuid
     *
     * @return $this
     */
    public function setCustomeruuid($customeruuid)
    {
        $this->container['customeruuid'] = $customeruuid;

        return $this;
    }

    /**
     * Gets imageuuid
     *
     * @return int
     */
    public function getImageuuid()
    {
        return $this->container['imageuuid'];
    }

    /**
     * Sets imageuuid
     *
     * @param int $imageuuid imageuuid
     *
     * @return $this
     */
    public function setImageuuid($imageuuid)
    {
        $this->container['imageuuid'] = $imageuuid;

        return $this;
    }

    /**
     * Gets flavoruuid
     *
     * @return int
     */
    public function getFlavoruuid()
    {
        return $this->container['flavoruuid'];
    }

    /**
     * Sets flavoruuid
     *
     * @param int $flavoruuid flavoruuid
     *
     * @return $this
     */
    public function setFlavoruuid($flavoruuid)
    {
        $this->container['flavoruuid'] = $flavoruuid;

        return $this;
    }

    /**
     * Gets datacenteruuid
     *
     * @return string
     */
    public function getDatacenteruuid()
    {
        return $this->container['datacenteruuid'];
    }

    /**
     * Sets datacenteruuid
     *
     * @param string $datacenteruuid datacenteruuid
     *
     * @return $this
     */
    public function setDatacenteruuid($datacenteruuid)
    {
        $this->container['datacenteruuid'] = $datacenteruuid;

        return $this;
    }

    /**
     * Gets config
     *
     * @return string
     */
    public function getConfig()
    {
        return $this->container['config'];
    }

    /**
     * Sets config
     *
     * @param string $config Boot configuration for VNF, base64 encoded
     *
     * @return $this
     */
    public function setConfig($config)
    {
        $this->container['config'] = $config;

        return $this;
    }

    /**
     * Gets topology_tag_uuid
     *
     * @return string|null
     */
    public function getTopologyTagUuid()
    {
        return $this->container['topology_tag_uuid'];
    }

    /**
     * Sets topology_tag_uuid
     *
     * @param string|null $topology_tag_uuid topology_tag_uuid
     *
     * @return $this
     */
    public function setTopologyTagUuid($topology_tag_uuid)
    {
        $this->container['topology_tag_uuid'] = $topology_tag_uuid;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


