<?php
/**
 * ExchangeProviderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  tpn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Telstra Programmable Network API
 *
 * Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.
 *
 * OpenAPI spec version: 2.4.2
 * Contact: pnapi-support@team.telstra.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace tpn;

/**
 * ExchangeProviderTest Class Doc Comment
 *
 * @category    Class
 * @description ExchangeProvider
 * @package     tpn
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ExchangeProviderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ExchangeProvider"
     */
    public function testExchangeProvider()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "is_provider"
     */
    public function testPropertyIsProvider()
    {
    }

    /**
     * Test attribute "visit_card_uuid"
     */
    public function testPropertyVisitCardUuid()
    {
    }

    /**
     * Test attribute "is_public"
     */
    public function testPropertyIsPublic()
    {
    }

    /**
     * Test attribute "pops"
     */
    public function testPropertyPops()
    {
    }

    /**
     * Test attribute "pending_requests_count"
     */
    public function testPropertyPendingRequestsCount()
    {
    }

    /**
     * Test attribute "approved_requests_count"
     */
    public function testPropertyApprovedRequestsCount()
    {
    }
}
