<?php
/**
 * ImageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  tpn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Telstra Programmable Network API
 *
 * Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.
 *
 * OpenAPI spec version: 2.4.2
 * Contact: pnapi-support@team.telstra.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace tpn;

/**
 * ImageTest Class Doc Comment
 *
 * @category    Class
 * @description Image
 * @package     tpn
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ImageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Image"
     */
    public function testImage()
    {
    }

    /**
     * Test attribute "brief_description"
     */
    public function testPropertyBriefDescription()
    {
    }

    /**
     * Test attribute "buyers"
     */
    public function testPropertyBuyers()
    {
    }

    /**
     * Test attribute "classifications"
     */
    public function testPropertyClassifications()
    {
    }

    /**
     * Test attribute "comments"
     */
    public function testPropertyComments()
    {
    }

    /**
     * Test attribute "create_at"
     */
    public function testPropertyCreateAt()
    {
    }

    /**
     * Test attribute "creator"
     */
    public function testPropertyCreator()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "eos"
     */
    public function testPropertyEos()
    {
    }

    /**
     * Test attribute "flavors"
     */
    public function testPropertyFlavors()
    {
    }

    /**
     * Test attribute "flavors_price"
     */
    public function testPropertyFlavorsPrice()
    {
    }

    /**
     * Test attribute "glance_comments"
     */
    public function testPropertyGlanceComments()
    {
    }

    /**
     * Test attribute "glance_image"
     */
    public function testPropertyGlanceImage()
    {
    }

    /**
     * Test attribute "glance_name"
     */
    public function testPropertyGlanceName()
    {
    }

    /**
     * Test attribute "glance_properties"
     */
    public function testPropertyGlanceProperties()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "image_format"
     */
    public function testPropertyImageFormat()
    {
    }

    /**
     * Test attribute "license_required"
     */
    public function testPropertyLicenseRequired()
    {
    }

    /**
     * Test attribute "logo"
     */
    public function testPropertyLogo()
    {
    }

    /**
     * Test attribute "max_ports"
     */
    public function testPropertyMaxPorts()
    {
    }

    /**
     * Test attribute "md5"
     */
    public function testPropertyMd5()
    {
    }

    /**
     * Test attribute "min_ports"
     */
    public function testPropertyMinPorts()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "os_version"
     */
    public function testPropertyOsVersion()
    {
    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {
    }

    /**
     * Test attribute "product"
     */
    public function testPropertyProduct()
    {
    }

    /**
     * Test attribute "publish_date"
     */
    public function testPropertyPublishDate()
    {
    }

    /**
     * Test attribute "restrict_vnc_console"
     */
    public function testPropertyRestrictVncConsole()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "support_hot_plug"
     */
    public function testPropertySupportHotPlug()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "upload_at"
     */
    public function testPropertyUploadAt()
    {
    }

    /**
     * Test attribute "vendor_name"
     */
    public function testPropertyVendorName()
    {
    }

    /**
     * Test attribute "zero_day_config_spec"
     */
    public function testPropertyZeroDayConfigSpec()
    {
    }
}
