<?php
/**
 * InlineResponse2006ParamsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  tpn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Telstra Programmable Network API
 *
 * Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.
 *
 * OpenAPI spec version: 2.4.2
 * Contact: pnapi-support@team.telstra.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace tpn;

/**
 * InlineResponse2006ParamsTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2006Params
 * @package     tpn
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse2006ParamsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2006Params"
     */
    public function testInlineResponse2006Params()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "bandwidth"
     */
    public function testPropertyBandwidth()
    {
    }

    /**
     * Test attribute "latency"
     */
    public function testPropertyLatency()
    {
    }

    /**
     * Test attribute "linkid"
     */
    public function testPropertyLinkid()
    {
    }

    /**
     * Test attribute "contractid"
     */
    public function testPropertyContractid()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "contract_status"
     */
    public function testPropertyContractStatus()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "deletedtimestamp"
     */
    public function testPropertyDeletedtimestamp()
    {
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
    }

    /**
     * Test attribute "connection"
     */
    public function testPropertyConnection()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "billing_id"
     */
    public function testPropertyBillingId()
    {
    }

    /**
     * Test attribute "renewal_option"
     */
    public function testPropertyRenewalOption()
    {
    }

    /**
     * Test attribute "contract_start_time"
     */
    public function testPropertyContractStartTime()
    {
    }

    /**
     * Test attribute "contract_end_time"
     */
    public function testPropertyContractEndTime()
    {
    }
}
