<?php
/**
 * InlineResponse2005DatacenterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  tpn
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Telstra Programmable Network API
 *
 * Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: pnapi-support@team.telstra.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace tpn;

/**
 * InlineResponse2005DatacenterTest Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse2005Datacenter
/**
 * @package     tpn
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2005DatacenterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2005Datacenter"
     */
    public function testInlineResponse2005Datacenter()
    {
    }

    /**
     * Test attribute "datacenteruuid"
     */
    public function testPropertyDatacenteruuid()
    {
    }

    /**
     * Test attribute "port"
     */
    public function testPropertyPort()
    {
    }
}
